name: loxa-rs

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: loxa-rs
    steps:
      - uses: actions/checkout@v4
        with:
          path: loxa-rs
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo fmt --check
      - run: cargo test
