project_name: loza

version: 2

builds:
  - id: loza-cli
    dir: ./cli
    main: ./cmd/loza
    binary: loza
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/astraive/loza/cli/internal/version.Version={{ .Version }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: loza-cli
    ids: [loza-cli]
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: "loza_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: Astraive
    name: loza
  name_template: "LOZA CLI {{ .Version }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^chore:"
      - "^ci:"
