// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: loxa/v1/collector.proto

package loxav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CollectorStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectorStatusRequest) Reset() {
	*x = CollectorStatusRequest{}
	mi := &file_loxa_v1_collector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectorStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectorStatusRequest) ProtoMessage() {}

func (x *CollectorStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loxa_v1_collector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectorStatusRequest.ProtoReflect.Descriptor instead.
func (*CollectorStatusRequest) Descriptor() ([]byte, []int) {
	return file_loxa_v1_collector_proto_rawDescGZIP(), []int{0}
}

type CollectorStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectorStatusResponse) Reset() {
	*x = CollectorStatusResponse{}
	mi := &file_loxa_v1_collector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectorStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectorStatusResponse) ProtoMessage() {}

func (x *CollectorStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loxa_v1_collector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectorStatusResponse.ProtoReflect.Descriptor instead.
func (*CollectorStatusResponse) Descriptor() ([]byte, []int) {
	return file_loxa_v1_collector_proto_rawDescGZIP(), []int{1}
}

func (x *CollectorStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type IngestBatch struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Events           []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	ApiKey           string                 `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`                      // inline API key for SDK connectors
	SourceService    string                 `protobuf:"bytes,3,opt,name=source_service,json=sourceService,proto3" json:"source_service,omitempty"` // SDK source service name
	SourceSdk        string                 `protobuf:"bytes,4,opt,name=source_sdk,json=sourceSdk,proto3" json:"source_sdk,omitempty"`             // SDK name (e.g., "loxa-js", "loxa-py")
	SourceSdkVersion string                 `protobuf:"bytes,5,opt,name=source_sdk_version,json=sourceSdkVersion,proto3" json:"source_sdk_version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *IngestBatch) Reset() {
	*x = IngestBatch{}
	mi := &file_loxa_v1_collector_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestBatch) ProtoMessage() {}

func (x *IngestBatch) ProtoReflect() protoreflect.Message {
	mi := &file_loxa_v1_collector_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestBatch.ProtoReflect.Descriptor instead.
func (*IngestBatch) Descriptor() ([]byte, []int) {
	return file_loxa_v1_collector_proto_rawDescGZIP(), []int{2}
}

func (x *IngestBatch) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *IngestBatch) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *IngestBatch) GetSourceService() string {
	if x != nil {
		return x.SourceService
	}
	return ""
}

func (x *IngestBatch) GetSourceSdk() string {
	if x != nil {
		return x.SourceSdk
	}
	return ""
}

func (x *IngestBatch) GetSourceSdkVersion() string {
	if x != nil {
		return x.SourceSdkVersion
	}
	return ""
}

type IngestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      int64                  `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Rejected      int64                  `protobuf:"varint,2,opt,name=rejected,proto3" json:"rejected,omitempty"`
	Invalid       int64                  `protobuf:"varint,3,opt,name=invalid,proto3" json:"invalid,omitempty"`
	Quarantined   int64                  `protobuf:"varint,4,opt,name=quarantined,proto3" json:"quarantined,omitempty"`
	Deduped       int64                  `protobuf:"varint,5,opt,name=deduped,proto3" json:"deduped,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Acks          []*EventAck            `protobuf:"bytes,7,rep,name=acks,proto3" json:"acks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestResponse) Reset() {
	*x = IngestResponse{}
	mi := &file_loxa_v1_collector_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestResponse) ProtoMessage() {}

func (x *IngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loxa_v1_collector_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestResponse.ProtoReflect.Descriptor instead.
func (*IngestResponse) Descriptor() ([]byte, []int) {
	return file_loxa_v1_collector_proto_rawDescGZIP(), []int{3}
}

func (x *IngestResponse) GetAccepted() int64 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

func (x *IngestResponse) GetRejected() int64 {
	if x != nil {
		return x.Rejected
	}
	return 0
}

func (x *IngestResponse) GetInvalid() int64 {
	if x != nil {
		return x.Invalid
	}
	return 0
}

func (x *IngestResponse) GetQuarantined() int64 {
	if x != nil {
		return x.Quarantined
	}
	return 0
}

func (x *IngestResponse) GetDeduped() int64 {
	if x != nil {
		return x.Deduped
	}
	return 0
}

func (x *IngestResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *IngestResponse) GetAcks() []*EventAck {
	if x != nil {
		return x.Acks
	}
	return nil
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_loxa_v1_collector_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loxa_v1_collector_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_loxa_v1_collector_proto_rawDescGZIP(), []int{4}
}

func (x *PingRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_loxa_v1_collector_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loxa_v1_collector_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_loxa_v1_collector_proto_rawDescGZIP(), []int{5}
}

func (x *PingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PingResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_loxa_v1_collector_proto protoreflect.FileDescriptor

const file_loxa_v1_collector_proto_rawDesc = "" +
	"\n" +
	"\x17loxa/v1/collector.proto\x12\aloxa.v1\x1a\x13loxa/v1/event.proto\x1a\x14loxa/v1/ingest.proto\"\x18\n" +
	"\x16CollectorStatusRequest\"1\n" +
	"\x17CollectorStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\xc2\x01\n" +
	"\vIngestBatch\x12&\n" +
	"\x06events\x18\x01 \x03(\v2\x0e.loxa.v1.EventR\x06events\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\x12%\n" +
	"\x0esource_service\x18\x03 \x01(\tR\rsourceService\x12\x1d\n" +
	"\n" +
	"source_sdk\x18\x04 \x01(\tR\tsourceSdk\x12,\n" +
	"\x12source_sdk_version\x18\x05 \x01(\tR\x10sourceSdkVersion\"\xea\x01\n" +
	"\x0eIngestResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\x03R\baccepted\x12\x1a\n" +
	"\brejected\x18\x02 \x01(\x03R\brejected\x12\x18\n" +
	"\ainvalid\x18\x03 \x01(\x03R\ainvalid\x12 \n" +
	"\vquarantined\x18\x04 \x01(\x03R\vquarantined\x12\x18\n" +
	"\adeduped\x18\x05 \x01(\x03R\adeduped\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\x12%\n" +
	"\x04acks\x18\a \x03(\v2\x11.loxa.v1.EventAckR\x04acks\"'\n" +
	"\vPingRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"@\n" +
	"\fPingResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion2\xab\x01\n" +
	"\x10CollectorService\x12K\n" +
	"\x06Health\x12\x1f.loxa.v1.CollectorStatusRequest\x1a .loxa.v1.CollectorStatusResponse\x12J\n" +
	"\x05Ready\x12\x1f.loxa.v1.CollectorStatusRequest\x1a .loxa.v1.CollectorStatusResponse2\xba\x01\n" +
	"\x0fCollectorIngest\x127\n" +
	"\x06Ingest\x12\x14.loxa.v1.IngestBatch\x1a\x17.loxa.v1.IngestResponse\x129\n" +
	"\fIngestStream\x12\x0e.loxa.v1.Event\x1a\x17.loxa.v1.IngestResponse(\x01\x123\n" +
	"\x04Ping\x12\x14.loxa.v1.PingRequest\x1a\x15.loxa.v1.PingResponseB4Z2github.com/astraive/loxa/spec/proto/loxa/v1;loxav1b\x06proto3"

var (
	file_loxa_v1_collector_proto_rawDescOnce sync.Once
	file_loxa_v1_collector_proto_rawDescData []byte
)

func file_loxa_v1_collector_proto_rawDescGZIP() []byte {
	file_loxa_v1_collector_proto_rawDescOnce.Do(func() {
		file_loxa_v1_collector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_loxa_v1_collector_proto_rawDesc), len(file_loxa_v1_collector_proto_rawDesc)))
	})
	return file_loxa_v1_collector_proto_rawDescData
}

var file_loxa_v1_collector_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_loxa_v1_collector_proto_goTypes = []any{
	(*CollectorStatusRequest)(nil),  // 0: loxa.v1.CollectorStatusRequest
	(*CollectorStatusResponse)(nil), // 1: loxa.v1.CollectorStatusResponse
	(*IngestBatch)(nil),             // 2: loxa.v1.IngestBatch
	(*IngestResponse)(nil),          // 3: loxa.v1.IngestResponse
	(*PingRequest)(nil),             // 4: loxa.v1.PingRequest
	(*PingResponse)(nil),            // 5: loxa.v1.PingResponse
	(*Event)(nil),                   // 6: loxa.v1.Event
	(*EventAck)(nil),                // 7: loxa.v1.EventAck
}
var file_loxa_v1_collector_proto_depIdxs = []int32{
	6, // 0: loxa.v1.IngestBatch.events:type_name -> loxa.v1.Event
	7, // 1: loxa.v1.IngestResponse.acks:type_name -> loxa.v1.EventAck
	0, // 2: loxa.v1.CollectorService.Health:input_type -> loxa.v1.CollectorStatusRequest
	0, // 3: loxa.v1.CollectorService.Ready:input_type -> loxa.v1.CollectorStatusRequest
	2, // 4: loxa.v1.CollectorIngest.Ingest:input_type -> loxa.v1.IngestBatch
	6, // 5: loxa.v1.CollectorIngest.IngestStream:input_type -> loxa.v1.Event
	4, // 6: loxa.v1.CollectorIngest.Ping:input_type -> loxa.v1.PingRequest
	1, // 7: loxa.v1.CollectorService.Health:output_type -> loxa.v1.CollectorStatusResponse
	1, // 8: loxa.v1.CollectorService.Ready:output_type -> loxa.v1.CollectorStatusResponse
	3, // 9: loxa.v1.CollectorIngest.Ingest:output_type -> loxa.v1.IngestResponse
	3, // 10: loxa.v1.CollectorIngest.IngestStream:output_type -> loxa.v1.IngestResponse
	5, // 11: loxa.v1.CollectorIngest.Ping:output_type -> loxa.v1.PingResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_loxa_v1_collector_proto_init() }
func file_loxa_v1_collector_proto_init() {
	if File_loxa_v1_collector_proto != nil {
		return
	}
	file_loxa_v1_event_proto_init()
	file_loxa_v1_ingest_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_loxa_v1_collector_proto_rawDesc), len(file_loxa_v1_collector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_loxa_v1_collector_proto_goTypes,
		DependencyIndexes: file_loxa_v1_collector_proto_depIdxs,
		MessageInfos:      file_loxa_v1_collector_proto_msgTypes,
	}.Build()
	File_loxa_v1_collector_proto = out.File
	file_loxa_v1_collector_proto_goTypes = nil
	file_loxa_v1_collector_proto_depIdxs = nil
}
