// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: loxa/v1/collector.proto

package loxav1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CollectorService_Health_FullMethodName = "/loxa.v1.CollectorService/Health"
	CollectorService_Ready_FullMethodName  = "/loxa.v1.CollectorService/Ready"
)

// CollectorServiceClient is the client API for CollectorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CollectorServiceClient interface {
	Health(ctx context.Context, in *CollectorStatusRequest, opts ...grpc.CallOption) (*CollectorStatusResponse, error)
	Ready(ctx context.Context, in *CollectorStatusRequest, opts ...grpc.CallOption) (*CollectorStatusResponse, error)
}

type collectorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCollectorServiceClient(cc grpc.ClientConnInterface) CollectorServiceClient {
	return &collectorServiceClient{cc}
}

func (c *collectorServiceClient) Health(ctx context.Context, in *CollectorStatusRequest, opts ...grpc.CallOption) (*CollectorStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CollectorStatusResponse)
	err := c.cc.Invoke(ctx, CollectorService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectorServiceClient) Ready(ctx context.Context, in *CollectorStatusRequest, opts ...grpc.CallOption) (*CollectorStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CollectorStatusResponse)
	err := c.cc.Invoke(ctx, CollectorService_Ready_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CollectorServiceServer is the server API for CollectorService service.
// All implementations must embed UnimplementedCollectorServiceServer
// for forward compatibility.
type CollectorServiceServer interface {
	Health(context.Context, *CollectorStatusRequest) (*CollectorStatusResponse, error)
	Ready(context.Context, *CollectorStatusRequest) (*CollectorStatusResponse, error)
	mustEmbedUnimplementedCollectorServiceServer()
}

// UnimplementedCollectorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCollectorServiceServer struct{}

func (UnimplementedCollectorServiceServer) Health(context.Context, *CollectorStatusRequest) (*CollectorStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedCollectorServiceServer) Ready(context.Context, *CollectorStatusRequest) (*CollectorStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ready not implemented")
}
func (UnimplementedCollectorServiceServer) mustEmbedUnimplementedCollectorServiceServer() {}
func (UnimplementedCollectorServiceServer) testEmbeddedByValue()                          {}

// UnsafeCollectorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CollectorServiceServer will
// result in compilation errors.
type UnsafeCollectorServiceServer interface {
	mustEmbedUnimplementedCollectorServiceServer()
}

func RegisterCollectorServiceServer(s grpc.ServiceRegistrar, srv CollectorServiceServer) {
	// If the following call panics, it indicates UnimplementedCollectorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CollectorService_ServiceDesc, srv)
}

func _CollectorService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectorStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollectorService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorServiceServer).Health(ctx, req.(*CollectorStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectorService_Ready_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectorStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorServiceServer).Ready(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollectorService_Ready_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorServiceServer).Ready(ctx, req.(*CollectorStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CollectorService_ServiceDesc is the grpc.ServiceDesc for CollectorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CollectorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "loxa.v1.CollectorService",
	HandlerType: (*CollectorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _CollectorService_Health_Handler,
		},
		{
			MethodName: "Ready",
			Handler:    _CollectorService_Ready_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "loxa/v1/collector.proto",
}

const (
	CollectorIngest_Ingest_FullMethodName       = "/loxa.v1.CollectorIngest/Ingest"
	CollectorIngest_IngestStream_FullMethodName = "/loxa.v1.CollectorIngest/IngestStream"
	CollectorIngest_Ping_FullMethodName         = "/loxa.v1.CollectorIngest/Ping"
)

// CollectorIngestClient is the client API for CollectorIngest service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// gRPC-based event ingestion for SDK lightweight connectors
type CollectorIngestClient interface {
	// Ingest a batch of events via gRPC (lightweight SDK connector)
	Ingest(ctx context.Context, in *IngestBatch, opts ...grpc.CallOption) (*IngestResponse, error)
	// Stream events for high-throughput ingestion
	IngestStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Event, IngestResponse], error)
	// Check ingestion health
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type collectorIngestClient struct {
	cc grpc.ClientConnInterface
}

func NewCollectorIngestClient(cc grpc.ClientConnInterface) CollectorIngestClient {
	return &collectorIngestClient{cc}
}

func (c *collectorIngestClient) Ingest(ctx context.Context, in *IngestBatch, opts ...grpc.CallOption) (*IngestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestResponse)
	err := c.cc.Invoke(ctx, CollectorIngest_Ingest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectorIngestClient) IngestStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Event, IngestResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CollectorIngest_ServiceDesc.Streams[0], CollectorIngest_IngestStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Event, IngestResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CollectorIngest_IngestStreamClient = grpc.ClientStreamingClient[Event, IngestResponse]

func (c *collectorIngestClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, CollectorIngest_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CollectorIngestServer is the server API for CollectorIngest service.
// All implementations must embed UnimplementedCollectorIngestServer
// for forward compatibility.
//
// gRPC-based event ingestion for SDK lightweight connectors
type CollectorIngestServer interface {
	// Ingest a batch of events via gRPC (lightweight SDK connector)
	Ingest(context.Context, *IngestBatch) (*IngestResponse, error)
	// Stream events for high-throughput ingestion
	IngestStream(grpc.ClientStreamingServer[Event, IngestResponse]) error
	// Check ingestion health
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	mustEmbedUnimplementedCollectorIngestServer()
}

// UnimplementedCollectorIngestServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCollectorIngestServer struct{}

func (UnimplementedCollectorIngestServer) Ingest(context.Context, *IngestBatch) (*IngestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ingest not implemented")
}
func (UnimplementedCollectorIngestServer) IngestStream(grpc.ClientStreamingServer[Event, IngestResponse]) error {
	return status.Error(codes.Unimplemented, "method IngestStream not implemented")
}
func (UnimplementedCollectorIngestServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedCollectorIngestServer) mustEmbedUnimplementedCollectorIngestServer() {}
func (UnimplementedCollectorIngestServer) testEmbeddedByValue()                         {}

// UnsafeCollectorIngestServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CollectorIngestServer will
// result in compilation errors.
type UnsafeCollectorIngestServer interface {
	mustEmbedUnimplementedCollectorIngestServer()
}

func RegisterCollectorIngestServer(s grpc.ServiceRegistrar, srv CollectorIngestServer) {
	// If the following call panics, it indicates UnimplementedCollectorIngestServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CollectorIngest_ServiceDesc, srv)
}

func _CollectorIngest_Ingest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorIngestServer).Ingest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollectorIngest_Ingest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorIngestServer).Ingest(ctx, req.(*IngestBatch))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectorIngest_IngestStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CollectorIngestServer).IngestStream(&grpc.GenericServerStream[Event, IngestResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CollectorIngest_IngestStreamServer = grpc.ClientStreamingServer[Event, IngestResponse]

func _CollectorIngest_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorIngestServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollectorIngest_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorIngestServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CollectorIngest_ServiceDesc is the grpc.ServiceDesc for CollectorIngest service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CollectorIngest_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "loxa.v1.CollectorIngest",
	HandlerType: (*CollectorIngestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ingest",
			Handler:    _CollectorIngest_Ingest_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _CollectorIngest_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "IngestStream",
			Handler:       _CollectorIngest_IngestStream_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "loxa/v1/collector.proto",
}
