// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: loxa/v1/ingest.proto

package loxav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RawEventBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*RawEvent            `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawEventBatch) Reset() {
	*x = RawEventBatch{}
	mi := &file_loxa_v1_ingest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawEventBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawEventBatch) ProtoMessage() {}

func (x *RawEventBatch) ProtoReflect() protoreflect.Message {
	mi := &file_loxa_v1_ingest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawEventBatch.ProtoReflect.Descriptor instead.
func (*RawEventBatch) Descriptor() ([]byte, []int) {
	return file_loxa_v1_ingest_proto_rawDescGZIP(), []int{0}
}

func (x *RawEventBatch) GetEvents() []*RawEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type RawEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawJson       string                 `protobuf:"bytes,1,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawEvent) Reset() {
	*x = RawEvent{}
	mi := &file_loxa_v1_ingest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawEvent) ProtoMessage() {}

func (x *RawEvent) ProtoReflect() protoreflect.Message {
	mi := &file_loxa_v1_ingest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawEvent.ProtoReflect.Descriptor instead.
func (*RawEvent) Descriptor() ([]byte, []int) {
	return file_loxa_v1_ingest_proto_rawDescGZIP(), []int{1}
}

func (x *RawEvent) GetRawJson() string {
	if x != nil {
		return x.RawJson
	}
	return ""
}

type EventAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Retryable     bool                   `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventAck) Reset() {
	*x = EventAck{}
	mi := &file_loxa_v1_ingest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventAck) ProtoMessage() {}

func (x *EventAck) ProtoReflect() protoreflect.Message {
	mi := &file_loxa_v1_ingest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventAck.ProtoReflect.Descriptor instead.
func (*EventAck) Descriptor() ([]byte, []int) {
	return file_loxa_v1_ingest_proto_rawDescGZIP(), []int{2}
}

func (x *EventAck) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EventAck) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EventAck) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *EventAck) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type PushResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      int64                  `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Rejected      int64                  `protobuf:"varint,2,opt,name=rejected,proto3" json:"rejected,omitempty"`
	Invalid       int64                  `protobuf:"varint,3,opt,name=invalid,proto3" json:"invalid,omitempty"`
	Deduped       int64                  `protobuf:"varint,4,opt,name=deduped,proto3" json:"deduped,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Acks          []*EventAck            `protobuf:"bytes,6,rep,name=acks,proto3" json:"acks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushResponse) Reset() {
	*x = PushResponse{}
	mi := &file_loxa_v1_ingest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushResponse) ProtoMessage() {}

func (x *PushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loxa_v1_ingest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushResponse.ProtoReflect.Descriptor instead.
func (*PushResponse) Descriptor() ([]byte, []int) {
	return file_loxa_v1_ingest_proto_rawDescGZIP(), []int{3}
}

func (x *PushResponse) GetAccepted() int64 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

func (x *PushResponse) GetRejected() int64 {
	if x != nil {
		return x.Rejected
	}
	return 0
}

func (x *PushResponse) GetInvalid() int64 {
	if x != nil {
		return x.Invalid
	}
	return 0
}

func (x *PushResponse) GetDeduped() int64 {
	if x != nil {
		return x.Deduped
	}
	return 0
}

func (x *PushResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *PushResponse) GetAcks() []*EventAck {
	if x != nil {
		return x.Acks
	}
	return nil
}

var File_loxa_v1_ingest_proto protoreflect.FileDescriptor

const file_loxa_v1_ingest_proto_rawDesc = "" +
	"\n" +
	"\x14loxa/v1/ingest.proto\x12\aloxa.v1\":\n" +
	"\rRawEventBatch\x12)\n" +
	"\x06events\x18\x01 \x03(\v2\x11.loxa.v1.RawEventR\x06events\"%\n" +
	"\bRawEvent\x12\x19\n" +
	"\braw_json\x18\x01 \x01(\tR\arawJson\"s\n" +
	"\bEventAck\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1c\n" +
	"\tretryable\x18\x03 \x01(\bR\tretryable\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\xc6\x01\n" +
	"\fPushResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\x03R\baccepted\x12\x1a\n" +
	"\brejected\x18\x02 \x01(\x03R\brejected\x12\x18\n" +
	"\ainvalid\x18\x03 \x01(\x03R\ainvalid\x12\x18\n" +
	"\adeduped\x18\x04 \x01(\x03R\adeduped\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x12%\n" +
	"\x04acks\x18\x06 \x03(\v2\x11.loxa.v1.EventAckR\x04acks2B\n" +
	"\tLogIngest\x125\n" +
	"\x04Push\x12\x16.loxa.v1.RawEventBatch\x1a\x15.loxa.v1.PushResponse2\x86\x01\n" +
	"\n" +
	"LoxaIngest\x127\n" +
	"\x06Ingest\x12\x16.loxa.v1.RawEventBatch\x1a\x15.loxa.v1.PushResponse\x12?\n" +
	"\fIngestStream\x12\x16.loxa.v1.RawEventBatch\x1a\x15.loxa.v1.PushResponse(\x01B4Z2github.com/astraive/loxa/spec/proto/loxa/v1;loxav1b\x06proto3"

var (
	file_loxa_v1_ingest_proto_rawDescOnce sync.Once
	file_loxa_v1_ingest_proto_rawDescData []byte
)

func file_loxa_v1_ingest_proto_rawDescGZIP() []byte {
	file_loxa_v1_ingest_proto_rawDescOnce.Do(func() {
		file_loxa_v1_ingest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_loxa_v1_ingest_proto_rawDesc), len(file_loxa_v1_ingest_proto_rawDesc)))
	})
	return file_loxa_v1_ingest_proto_rawDescData
}

var file_loxa_v1_ingest_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_loxa_v1_ingest_proto_goTypes = []any{
	(*RawEventBatch)(nil), // 0: loxa.v1.RawEventBatch
	(*RawEvent)(nil),      // 1: loxa.v1.RawEvent
	(*EventAck)(nil),      // 2: loxa.v1.EventAck
	(*PushResponse)(nil),  // 3: loxa.v1.PushResponse
}
var file_loxa_v1_ingest_proto_depIdxs = []int32{
	1, // 0: loxa.v1.RawEventBatch.events:type_name -> loxa.v1.RawEvent
	2, // 1: loxa.v1.PushResponse.acks:type_name -> loxa.v1.EventAck
	0, // 2: loxa.v1.LogIngest.Push:input_type -> loxa.v1.RawEventBatch
	0, // 3: loxa.v1.LoxaIngest.Ingest:input_type -> loxa.v1.RawEventBatch
	0, // 4: loxa.v1.LoxaIngest.IngestStream:input_type -> loxa.v1.RawEventBatch
	3, // 5: loxa.v1.LogIngest.Push:output_type -> loxa.v1.PushResponse
	3, // 6: loxa.v1.LoxaIngest.Ingest:output_type -> loxa.v1.PushResponse
	3, // 7: loxa.v1.LoxaIngest.IngestStream:output_type -> loxa.v1.PushResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_loxa_v1_ingest_proto_init() }
func file_loxa_v1_ingest_proto_init() {
	if File_loxa_v1_ingest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_loxa_v1_ingest_proto_rawDesc), len(file_loxa_v1_ingest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_loxa_v1_ingest_proto_goTypes,
		DependencyIndexes: file_loxa_v1_ingest_proto_depIdxs,
		MessageInfos:      file_loxa_v1_ingest_proto_msgTypes,
	}.Build()
	File_loxa_v1_ingest_proto = out.File
	file_loxa_v1_ingest_proto_goTypes = nil
	file_loxa_v1_ingest_proto_depIdxs = nil
}
