// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: loxa/v1/cortex.proto

package loxav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthzRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthzRequest) Reset() {
	*x = HealthzRequest{}
	mi := &file_loxa_v1_cortex_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthzRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthzRequest) ProtoMessage() {}

func (x *HealthzRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loxa_v1_cortex_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthzRequest.ProtoReflect.Descriptor instead.
func (*HealthzRequest) Descriptor() ([]byte, []int) {
	return file_loxa_v1_cortex_proto_rawDescGZIP(), []int{0}
}

type HealthzResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthzResponse) Reset() {
	*x = HealthzResponse{}
	mi := &file_loxa_v1_cortex_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthzResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthzResponse) ProtoMessage() {}

func (x *HealthzResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loxa_v1_cortex_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthzResponse.ProtoReflect.Descriptor instead.
func (*HealthzResponse) Descriptor() ([]byte, []int) {
	return file_loxa_v1_cortex_proto_rawDescGZIP(), []int{1}
}

func (x *HealthzResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type IngestEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Service       string                 `protobuf:"bytes,4,opt,name=service,proto3" json:"service,omitempty"`
	TraceId       string                 `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	IncidentId    string                 `protobuf:"bytes,6,opt,name=incident_id,json=incidentId,proto3" json:"incident_id,omitempty"`
	Provenance    string                 `protobuf:"bytes,7,opt,name=provenance,proto3" json:"provenance,omitempty"`
	Raw           *structpb.Struct       `protobuf:"bytes,8,opt,name=raw,proto3" json:"raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestEventRequest) Reset() {
	*x = IngestEventRequest{}
	mi := &file_loxa_v1_cortex_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestEventRequest) ProtoMessage() {}

func (x *IngestEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loxa_v1_cortex_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestEventRequest.ProtoReflect.Descriptor instead.
func (*IngestEventRequest) Descriptor() ([]byte, []int) {
	return file_loxa_v1_cortex_proto_rawDescGZIP(), []int{2}
}

func (x *IngestEventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IngestEventRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *IngestEventRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *IngestEventRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *IngestEventRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *IngestEventRequest) GetIncidentId() string {
	if x != nil {
		return x.IncidentId
	}
	return ""
}

func (x *IngestEventRequest) GetProvenance() string {
	if x != nil {
		return x.Provenance
	}
	return ""
}

func (x *IngestEventRequest) GetRaw() *structpb.Struct {
	if x != nil {
		return x.Raw
	}
	return nil
}

type IngestEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestEventResponse) Reset() {
	*x = IngestEventResponse{}
	mi := &file_loxa_v1_cortex_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestEventResponse) ProtoMessage() {}

func (x *IngestEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loxa_v1_cortex_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestEventResponse.ProtoReflect.Descriptor instead.
func (*IngestEventResponse) Descriptor() ([]byte, []int) {
	return file_loxa_v1_cortex_proto_rawDescGZIP(), []int{3}
}

func (x *IngestEventResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type IngestBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*IngestEventRequest  `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestBatchRequest) Reset() {
	*x = IngestBatchRequest{}
	mi := &file_loxa_v1_cortex_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestBatchRequest) ProtoMessage() {}

func (x *IngestBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loxa_v1_cortex_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestBatchRequest.ProtoReflect.Descriptor instead.
func (*IngestBatchRequest) Descriptor() ([]byte, []int) {
	return file_loxa_v1_cortex_proto_rawDescGZIP(), []int{4}
}

func (x *IngestBatchRequest) GetEvents() []*IngestEventRequest {
	if x != nil {
		return x.Events
	}
	return nil
}

type IngestBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestBatchResponse) Reset() {
	*x = IngestBatchResponse{}
	mi := &file_loxa_v1_cortex_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestBatchResponse) ProtoMessage() {}

func (x *IngestBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loxa_v1_cortex_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestBatchResponse.ProtoReflect.Descriptor instead.
func (*IngestBatchResponse) Descriptor() ([]byte, []int) {
	return file_loxa_v1_cortex_proto_rawDescGZIP(), []int{5}
}

func (x *IngestBatchResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *IngestBatchResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ReconstructRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IncidentId    string                 `protobuf:"bytes,1,opt,name=incident_id,json=incidentId,proto3" json:"incident_id,omitempty"`
	Mode          string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconstructRequest) Reset() {
	*x = ReconstructRequest{}
	mi := &file_loxa_v1_cortex_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconstructRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconstructRequest) ProtoMessage() {}

func (x *ReconstructRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loxa_v1_cortex_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconstructRequest.ProtoReflect.Descriptor instead.
func (*ReconstructRequest) Descriptor() ([]byte, []int) {
	return file_loxa_v1_cortex_proto_rawDescGZIP(), []int{6}
}

func (x *ReconstructRequest) GetIncidentId() string {
	if x != nil {
		return x.IncidentId
	}
	return ""
}

func (x *ReconstructRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type GraphNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	NodeType      string                 `protobuf:"bytes,3,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphNode) Reset() {
	*x = GraphNode{}
	mi := &file_loxa_v1_cortex_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphNode) ProtoMessage() {}

func (x *GraphNode) ProtoReflect() protoreflect.Message {
	mi := &file_loxa_v1_cortex_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphNode.ProtoReflect.Descriptor instead.
func (*GraphNode) Descriptor() ([]byte, []int) {
	return file_loxa_v1_cortex_proto_rawDescGZIP(), []int{7}
}

func (x *GraphNode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GraphNode) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *GraphNode) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

type GraphEdge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	EdgeType      string                 `protobuf:"bytes,3,opt,name=edge_type,json=edgeType,proto3" json:"edge_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphEdge) Reset() {
	*x = GraphEdge{}
	mi := &file_loxa_v1_cortex_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphEdge) ProtoMessage() {}

func (x *GraphEdge) ProtoReflect() protoreflect.Message {
	mi := &file_loxa_v1_cortex_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphEdge.ProtoReflect.Descriptor instead.
func (*GraphEdge) Descriptor() ([]byte, []int) {
	return file_loxa_v1_cortex_proto_rawDescGZIP(), []int{8}
}

func (x *GraphEdge) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *GraphEdge) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *GraphEdge) GetEdgeType() string {
	if x != nil {
		return x.EdgeType
	}
	return ""
}

type ReconstructResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	IncidentId       string                 `protobuf:"bytes,1,opt,name=incident_id,json=incidentId,proto3" json:"incident_id,omitempty"`
	Status           string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Severity         string                 `protobuf:"bytes,3,opt,name=severity,proto3" json:"severity,omitempty"`
	PrimaryService   string                 `protobuf:"bytes,4,opt,name=primary_service,json=primaryService,proto3" json:"primary_service,omitempty"`
	AffectedServices []string               `protobuf:"bytes,5,rep,name=affected_services,json=affectedServices,proto3" json:"affected_services,omitempty"`
	Nodes            []*GraphNode           `protobuf:"bytes,6,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges            []*GraphEdge           `protobuf:"bytes,7,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReconstructResponse) Reset() {
	*x = ReconstructResponse{}
	mi := &file_loxa_v1_cortex_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconstructResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconstructResponse) ProtoMessage() {}

func (x *ReconstructResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loxa_v1_cortex_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconstructResponse.ProtoReflect.Descriptor instead.
func (*ReconstructResponse) Descriptor() ([]byte, []int) {
	return file_loxa_v1_cortex_proto_rawDescGZIP(), []int{9}
}

func (x *ReconstructResponse) GetIncidentId() string {
	if x != nil {
		return x.IncidentId
	}
	return ""
}

func (x *ReconstructResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReconstructResponse) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *ReconstructResponse) GetPrimaryService() string {
	if x != nil {
		return x.PrimaryService
	}
	return ""
}

func (x *ReconstructResponse) GetAffectedServices() []string {
	if x != nil {
		return x.AffectedServices
	}
	return nil
}

func (x *ReconstructResponse) GetNodes() []*GraphNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ReconstructResponse) GetEdges() []*GraphEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

type GetGraphRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	IncidentId    string                 `protobuf:"bytes,2,opt,name=incident_id,json=incidentId,proto3" json:"incident_id,omitempty"`
	Depth         int32                  `protobuf:"varint,3,opt,name=depth,proto3" json:"depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGraphRequest) Reset() {
	*x = GetGraphRequest{}
	mi := &file_loxa_v1_cortex_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGraphRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGraphRequest) ProtoMessage() {}

func (x *GetGraphRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loxa_v1_cortex_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGraphRequest.ProtoReflect.Descriptor instead.
func (*GetGraphRequest) Descriptor() ([]byte, []int) {
	return file_loxa_v1_cortex_proto_rawDescGZIP(), []int{10}
}

func (x *GetGraphRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *GetGraphRequest) GetIncidentId() string {
	if x != nil {
		return x.IncidentId
	}
	return ""
}

func (x *GetGraphRequest) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

type GetGraphResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*GraphNode           `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges         []*GraphEdge           `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGraphResponse) Reset() {
	*x = GetGraphResponse{}
	mi := &file_loxa_v1_cortex_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGraphResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGraphResponse) ProtoMessage() {}

func (x *GetGraphResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loxa_v1_cortex_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGraphResponse.ProtoReflect.Descriptor instead.
func (*GetGraphResponse) Descriptor() ([]byte, []int) {
	return file_loxa_v1_cortex_proto_rawDescGZIP(), []int{11}
}

func (x *GetGraphResponse) GetNodes() []*GraphNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *GetGraphResponse) GetEdges() []*GraphEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

type RecordFeedbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IncidentId    string                 `protobuf:"bytes,1,opt,name=incident_id,json=incidentId,proto3" json:"incident_id,omitempty"`
	RemediationId string                 `protobuf:"bytes,2,opt,name=remediation_id,json=remediationId,proto3" json:"remediation_id,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Notes         string                 `protobuf:"bytes,4,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordFeedbackRequest) Reset() {
	*x = RecordFeedbackRequest{}
	mi := &file_loxa_v1_cortex_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordFeedbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordFeedbackRequest) ProtoMessage() {}

func (x *RecordFeedbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loxa_v1_cortex_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordFeedbackRequest.ProtoReflect.Descriptor instead.
func (*RecordFeedbackRequest) Descriptor() ([]byte, []int) {
	return file_loxa_v1_cortex_proto_rawDescGZIP(), []int{12}
}

func (x *RecordFeedbackRequest) GetIncidentId() string {
	if x != nil {
		return x.IncidentId
	}
	return ""
}

func (x *RecordFeedbackRequest) GetRemediationId() string {
	if x != nil {
		return x.RemediationId
	}
	return ""
}

func (x *RecordFeedbackRequest) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RecordFeedbackRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type RecordFeedbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordFeedbackResponse) Reset() {
	*x = RecordFeedbackResponse{}
	mi := &file_loxa_v1_cortex_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordFeedbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordFeedbackResponse) ProtoMessage() {}

func (x *RecordFeedbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loxa_v1_cortex_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordFeedbackResponse.ProtoReflect.Descriptor instead.
func (*RecordFeedbackResponse) Descriptor() ([]byte, []int) {
	return file_loxa_v1_cortex_proto_rawDescGZIP(), []int{13}
}

func (x *RecordFeedbackResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type StreamEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IncidentId    string                 `protobuf:"bytes,1,opt,name=incident_id,json=incidentId,proto3" json:"incident_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_loxa_v1_cortex_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loxa_v1_cortex_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_loxa_v1_cortex_proto_rawDescGZIP(), []int{14}
}

func (x *StreamEventsRequest) GetIncidentId() string {
	if x != nil {
		return x.IncidentId
	}
	return ""
}

var File_loxa_v1_cortex_proto protoreflect.FileDescriptor

const file_loxa_v1_cortex_proto_rawDesc = "" +
	"\n" +
	"\x14loxa/v1/cortex.proto\x12\aloxa.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x10\n" +
	"\x0eHealthzRequest\")\n" +
	"\x0fHealthzResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x93\x02\n" +
	"\x12IngestEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x18\n" +
	"\aservice\x18\x04 \x01(\tR\aservice\x12\x19\n" +
	"\btrace_id\x18\x05 \x01(\tR\atraceId\x12\x1f\n" +
	"\vincident_id\x18\x06 \x01(\tR\n" +
	"incidentId\x12\x1e\n" +
	"\n" +
	"provenance\x18\a \x01(\tR\n" +
	"provenance\x12)\n" +
	"\x03raw\x18\b \x01(\v2\x17.google.protobuf.StructR\x03raw\"-\n" +
	"\x13IngestEventResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"I\n" +
	"\x12IngestBatchRequest\x123\n" +
	"\x06events\x18\x01 \x03(\v2\x1b.loxa.v1.IngestEventRequestR\x06events\"C\n" +
	"\x13IngestBatchResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"I\n" +
	"\x12ReconstructRequest\x12\x1f\n" +
	"\vincident_id\x18\x01 \x01(\tR\n" +
	"incidentId\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\"R\n" +
	"\tGraphNode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x1b\n" +
	"\tnode_type\x18\x03 \x01(\tR\bnodeType\"L\n" +
	"\tGraphEdge\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x1b\n" +
	"\tedge_type\x18\x03 \x01(\tR\bedgeType\"\x94\x02\n" +
	"\x13ReconstructResponse\x12\x1f\n" +
	"\vincident_id\x18\x01 \x01(\tR\n" +
	"incidentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1a\n" +
	"\bseverity\x18\x03 \x01(\tR\bseverity\x12'\n" +
	"\x0fprimary_service\x18\x04 \x01(\tR\x0eprimaryService\x12+\n" +
	"\x11affected_services\x18\x05 \x03(\tR\x10affectedServices\x12(\n" +
	"\x05nodes\x18\x06 \x03(\v2\x12.loxa.v1.GraphNodeR\x05nodes\x12(\n" +
	"\x05edges\x18\a \x03(\v2\x12.loxa.v1.GraphEdgeR\x05edges\"b\n" +
	"\x0fGetGraphRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x1f\n" +
	"\vincident_id\x18\x02 \x01(\tR\n" +
	"incidentId\x12\x14\n" +
	"\x05depth\x18\x03 \x01(\x05R\x05depth\"f\n" +
	"\x10GetGraphResponse\x12(\n" +
	"\x05nodes\x18\x01 \x03(\v2\x12.loxa.v1.GraphNodeR\x05nodes\x12(\n" +
	"\x05edges\x18\x02 \x03(\v2\x12.loxa.v1.GraphEdgeR\x05edges\"\x8f\x01\n" +
	"\x15RecordFeedbackRequest\x12\x1f\n" +
	"\vincident_id\x18\x01 \x01(\tR\n" +
	"incidentId\x12%\n" +
	"\x0eremediation_id\x18\x02 \x01(\tR\rremediationId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x14\n" +
	"\x05notes\x18\x04 \x01(\tR\x05notes\"0\n" +
	"\x16RecordFeedbackResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"6\n" +
	"\x13StreamEventsRequest\x12\x1f\n" +
	"\vincident_id\x18\x01 \x01(\tR\n" +
	"incidentId2\x8c\x04\n" +
	"\rCortexService\x12<\n" +
	"\aHealthz\x12\x17.loxa.v1.HealthzRequest\x1a\x18.loxa.v1.HealthzResponse\x12H\n" +
	"\vIngestEvent\x12\x1b.loxa.v1.IngestEventRequest\x1a\x1c.loxa.v1.IngestEventResponse\x12H\n" +
	"\vIngestBatch\x12\x1b.loxa.v1.IngestBatchRequest\x1a\x1c.loxa.v1.IngestBatchResponse\x12H\n" +
	"\vReconstruct\x12\x1b.loxa.v1.ReconstructRequest\x1a\x1c.loxa.v1.ReconstructResponse\x12?\n" +
	"\bGetGraph\x12\x18.loxa.v1.GetGraphRequest\x1a\x19.loxa.v1.GetGraphResponse\x12Q\n" +
	"\x0eRecordFeedback\x12\x1e.loxa.v1.RecordFeedbackRequest\x1a\x1f.loxa.v1.RecordFeedbackResponse\x12K\n" +
	"\fStreamEvents\x12\x1c.loxa.v1.StreamEventsRequest\x1a\x1b.loxa.v1.IngestEventRequest0\x01B4Z2github.com/astraive/loxa-spec/proto/loxa/v1;loxav1b\x06proto3"

var (
	file_loxa_v1_cortex_proto_rawDescOnce sync.Once
	file_loxa_v1_cortex_proto_rawDescData []byte
)

func file_loxa_v1_cortex_proto_rawDescGZIP() []byte {
	file_loxa_v1_cortex_proto_rawDescOnce.Do(func() {
		file_loxa_v1_cortex_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_loxa_v1_cortex_proto_rawDesc), len(file_loxa_v1_cortex_proto_rawDesc)))
	})
	return file_loxa_v1_cortex_proto_rawDescData
}

var file_loxa_v1_cortex_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_loxa_v1_cortex_proto_goTypes = []any{
	(*HealthzRequest)(nil),         // 0: loxa.v1.HealthzRequest
	(*HealthzResponse)(nil),        // 1: loxa.v1.HealthzResponse
	(*IngestEventRequest)(nil),     // 2: loxa.v1.IngestEventRequest
	(*IngestEventResponse)(nil),    // 3: loxa.v1.IngestEventResponse
	(*IngestBatchRequest)(nil),     // 4: loxa.v1.IngestBatchRequest
	(*IngestBatchResponse)(nil),    // 5: loxa.v1.IngestBatchResponse
	(*ReconstructRequest)(nil),     // 6: loxa.v1.ReconstructRequest
	(*GraphNode)(nil),              // 7: loxa.v1.GraphNode
	(*GraphEdge)(nil),              // 8: loxa.v1.GraphEdge
	(*ReconstructResponse)(nil),    // 9: loxa.v1.ReconstructResponse
	(*GetGraphRequest)(nil),        // 10: loxa.v1.GetGraphRequest
	(*GetGraphResponse)(nil),       // 11: loxa.v1.GetGraphResponse
	(*RecordFeedbackRequest)(nil),  // 12: loxa.v1.RecordFeedbackRequest
	(*RecordFeedbackResponse)(nil), // 13: loxa.v1.RecordFeedbackResponse
	(*StreamEventsRequest)(nil),    // 14: loxa.v1.StreamEventsRequest
	(*timestamppb.Timestamp)(nil),  // 15: google.protobuf.Timestamp
	(*structpb.Struct)(nil),        // 16: google.protobuf.Struct
}
var file_loxa_v1_cortex_proto_depIdxs = []int32{
	15, // 0: loxa.v1.IngestEventRequest.timestamp:type_name -> google.protobuf.Timestamp
	16, // 1: loxa.v1.IngestEventRequest.raw:type_name -> google.protobuf.Struct
	2,  // 2: loxa.v1.IngestBatchRequest.events:type_name -> loxa.v1.IngestEventRequest
	7,  // 3: loxa.v1.ReconstructResponse.nodes:type_name -> loxa.v1.GraphNode
	8,  // 4: loxa.v1.ReconstructResponse.edges:type_name -> loxa.v1.GraphEdge
	7,  // 5: loxa.v1.GetGraphResponse.nodes:type_name -> loxa.v1.GraphNode
	8,  // 6: loxa.v1.GetGraphResponse.edges:type_name -> loxa.v1.GraphEdge
	0,  // 7: loxa.v1.CortexService.Healthz:input_type -> loxa.v1.HealthzRequest
	2,  // 8: loxa.v1.CortexService.IngestEvent:input_type -> loxa.v1.IngestEventRequest
	4,  // 9: loxa.v1.CortexService.IngestBatch:input_type -> loxa.v1.IngestBatchRequest
	6,  // 10: loxa.v1.CortexService.Reconstruct:input_type -> loxa.v1.ReconstructRequest
	10, // 11: loxa.v1.CortexService.GetGraph:input_type -> loxa.v1.GetGraphRequest
	12, // 12: loxa.v1.CortexService.RecordFeedback:input_type -> loxa.v1.RecordFeedbackRequest
	14, // 13: loxa.v1.CortexService.StreamEvents:input_type -> loxa.v1.StreamEventsRequest
	1,  // 14: loxa.v1.CortexService.Healthz:output_type -> loxa.v1.HealthzResponse
	3,  // 15: loxa.v1.CortexService.IngestEvent:output_type -> loxa.v1.IngestEventResponse
	5,  // 16: loxa.v1.CortexService.IngestBatch:output_type -> loxa.v1.IngestBatchResponse
	9,  // 17: loxa.v1.CortexService.Reconstruct:output_type -> loxa.v1.ReconstructResponse
	11, // 18: loxa.v1.CortexService.GetGraph:output_type -> loxa.v1.GetGraphResponse
	13, // 19: loxa.v1.CortexService.RecordFeedback:output_type -> loxa.v1.RecordFeedbackResponse
	2,  // 20: loxa.v1.CortexService.StreamEvents:output_type -> loxa.v1.IngestEventRequest
	14, // [14:21] is the sub-list for method output_type
	7,  // [7:14] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_loxa_v1_cortex_proto_init() }
func file_loxa_v1_cortex_proto_init() {
	if File_loxa_v1_cortex_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_loxa_v1_cortex_proto_rawDesc), len(file_loxa_v1_cortex_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_loxa_v1_cortex_proto_goTypes,
		DependencyIndexes: file_loxa_v1_cortex_proto_depIdxs,
		MessageInfos:      file_loxa_v1_cortex_proto_msgTypes,
	}.Build()
	File_loxa_v1_cortex_proto = out.File
	file_loxa_v1_cortex_proto_goTypes = nil
	file_loxa_v1_cortex_proto_depIdxs = nil
}
