// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: loxa/v1/event.proto

package loxav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventKind int32

const (
	EventKind_EVENT_KIND_UNSPECIFIED EventKind = 0
	EventKind_EVENT_KIND_EVENT       EventKind = 1
	EventKind_EVENT_KIND_HTTP        EventKind = 2
	EventKind_EVENT_KIND_JOB         EventKind = 3
	EventKind_EVENT_KIND_QUEUE       EventKind = 4
	EventKind_EVENT_KIND_CLI         EventKind = 5
	EventKind_EVENT_KIND_CRON        EventKind = 6
	EventKind_EVENT_KIND_LOG         EventKind = 7
	EventKind_EVENT_KIND_CHECKPOINT  EventKind = 8
)

// Enum value maps for EventKind.
var (
	EventKind_name = map[int32]string{
		0: "EVENT_KIND_UNSPECIFIED",
		1: "EVENT_KIND_EVENT",
		2: "EVENT_KIND_HTTP",
		3: "EVENT_KIND_JOB",
		4: "EVENT_KIND_QUEUE",
		5: "EVENT_KIND_CLI",
		6: "EVENT_KIND_CRON",
		7: "EVENT_KIND_LOG",
		8: "EVENT_KIND_CHECKPOINT",
	}
	EventKind_value = map[string]int32{
		"EVENT_KIND_UNSPECIFIED": 0,
		"EVENT_KIND_EVENT":       1,
		"EVENT_KIND_HTTP":        2,
		"EVENT_KIND_JOB":         3,
		"EVENT_KIND_QUEUE":       4,
		"EVENT_KIND_CLI":         5,
		"EVENT_KIND_CRON":        6,
		"EVENT_KIND_LOG":         7,
		"EVENT_KIND_CHECKPOINT":  8,
	}
)

func (x EventKind) Enum() *EventKind {
	p := new(EventKind)
	*p = x
	return p
}

func (x EventKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventKind) Descriptor() protoreflect.EnumDescriptor {
	return file_loxa_v1_event_proto_enumTypes[0].Descriptor()
}

func (EventKind) Type() protoreflect.EnumType {
	return &file_loxa_v1_event_proto_enumTypes[0]
}

func (x EventKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventKind.Descriptor instead.
func (EventKind) EnumDescriptor() ([]byte, []int) {
	return file_loxa_v1_event_proto_rawDescGZIP(), []int{0}
}

type EventLevel int32

const (
	EventLevel_EVENT_LEVEL_UNSPECIFIED EventLevel = 0
	EventLevel_EVENT_LEVEL_DEBUG       EventLevel = 1
	EventLevel_EVENT_LEVEL_INFO        EventLevel = 2
	EventLevel_EVENT_LEVEL_WARN        EventLevel = 3
	EventLevel_EVENT_LEVEL_ERROR       EventLevel = 4
	EventLevel_EVENT_LEVEL_FATAL       EventLevel = 5
)

// Enum value maps for EventLevel.
var (
	EventLevel_name = map[int32]string{
		0: "EVENT_LEVEL_UNSPECIFIED",
		1: "EVENT_LEVEL_DEBUG",
		2: "EVENT_LEVEL_INFO",
		3: "EVENT_LEVEL_WARN",
		4: "EVENT_LEVEL_ERROR",
		5: "EVENT_LEVEL_FATAL",
	}
	EventLevel_value = map[string]int32{
		"EVENT_LEVEL_UNSPECIFIED": 0,
		"EVENT_LEVEL_DEBUG":       1,
		"EVENT_LEVEL_INFO":        2,
		"EVENT_LEVEL_WARN":        3,
		"EVENT_LEVEL_ERROR":       4,
		"EVENT_LEVEL_FATAL":       5,
	}
)

func (x EventLevel) Enum() *EventLevel {
	p := new(EventLevel)
	*p = x
	return p
}

func (x EventLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_loxa_v1_event_proto_enumTypes[1].Descriptor()
}

func (EventLevel) Type() protoreflect.EnumType {
	return &file_loxa_v1_event_proto_enumTypes[1]
}

func (x EventLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventLevel.Descriptor instead.
func (EventLevel) EnumDescriptor() ([]byte, []int) {
	return file_loxa_v1_event_proto_rawDescGZIP(), []int{1}
}

type EventOutcome int32

const (
	EventOutcome_EVENT_OUTCOME_UNSPECIFIED EventOutcome = 0
	EventOutcome_EVENT_OUTCOME_SUCCESS     EventOutcome = 1
	EventOutcome_EVENT_OUTCOME_ERROR       EventOutcome = 2
	EventOutcome_EVENT_OUTCOME_TIMEOUT     EventOutcome = 3
	EventOutcome_EVENT_OUTCOME_CANCELLED   EventOutcome = 4
	EventOutcome_EVENT_OUTCOME_REJECTED    EventOutcome = 5
	EventOutcome_EVENT_OUTCOME_UNKNOWN     EventOutcome = 6
)

// Enum value maps for EventOutcome.
var (
	EventOutcome_name = map[int32]string{
		0: "EVENT_OUTCOME_UNSPECIFIED",
		1: "EVENT_OUTCOME_SUCCESS",
		2: "EVENT_OUTCOME_ERROR",
		3: "EVENT_OUTCOME_TIMEOUT",
		4: "EVENT_OUTCOME_CANCELLED",
		5: "EVENT_OUTCOME_REJECTED",
		6: "EVENT_OUTCOME_UNKNOWN",
	}
	EventOutcome_value = map[string]int32{
		"EVENT_OUTCOME_UNSPECIFIED": 0,
		"EVENT_OUTCOME_SUCCESS":     1,
		"EVENT_OUTCOME_ERROR":       2,
		"EVENT_OUTCOME_TIMEOUT":     3,
		"EVENT_OUTCOME_CANCELLED":   4,
		"EVENT_OUTCOME_REJECTED":    5,
		"EVENT_OUTCOME_UNKNOWN":     6,
	}
)

func (x EventOutcome) Enum() *EventOutcome {
	p := new(EventOutcome)
	*p = x
	return p
}

func (x EventOutcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventOutcome) Descriptor() protoreflect.EnumDescriptor {
	return file_loxa_v1_event_proto_enumTypes[2].Descriptor()
}

func (EventOutcome) Type() protoreflect.EnumType {
	return &file_loxa_v1_event_proto_enumTypes[2]
}

func (x EventOutcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventOutcome.Descriptor instead.
func (EventOutcome) EnumDescriptor() ([]byte, []int) {
	return file_loxa_v1_event_proto_rawDescGZIP(), []int{2}
}

type HttpContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Route         string                 `protobuf:"bytes,3,opt,name=route,proto3" json:"route,omitempty"`
	StatusCode    int32                  `protobuf:"varint,4,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ClientIp      string                 `protobuf:"bytes,5,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	UserAgent     string                 `protobuf:"bytes,6,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	Url           string                 `protobuf:"bytes,7,opt,name=url,proto3" json:"url,omitempty"`
	Host          string                 `protobuf:"bytes,8,opt,name=host,proto3" json:"host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpContext) Reset() {
	*x = HttpContext{}
	mi := &file_loxa_v1_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpContext) ProtoMessage() {}

func (x *HttpContext) ProtoReflect() protoreflect.Message {
	mi := &file_loxa_v1_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpContext.ProtoReflect.Descriptor instead.
func (*HttpContext) Descriptor() ([]byte, []int) {
	return file_loxa_v1_event_proto_rawDescGZIP(), []int{0}
}

func (x *HttpContext) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HttpContext) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HttpContext) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

func (x *HttpContext) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *HttpContext) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *HttpContext) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *HttpContext) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *HttpContext) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

type ErrorContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Retriable     bool                   `protobuf:"varint,4,opt,name=retriable,proto3" json:"retriable,omitempty"`
	Cause         string                 `protobuf:"bytes,5,opt,name=cause,proto3" json:"cause,omitempty"`
	Stack         string                 `protobuf:"bytes,6,opt,name=stack,proto3" json:"stack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorContext) Reset() {
	*x = ErrorContext{}
	mi := &file_loxa_v1_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorContext) ProtoMessage() {}

func (x *ErrorContext) ProtoReflect() protoreflect.Message {
	mi := &file_loxa_v1_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorContext.ProtoReflect.Descriptor instead.
func (*ErrorContext) Descriptor() ([]byte, []int) {
	return file_loxa_v1_event_proto_rawDescGZIP(), []int{1}
}

func (x *ErrorContext) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ErrorContext) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorContext) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorContext) GetRetriable() bool {
	if x != nil {
		return x.Retriable
	}
	return false
}

func (x *ErrorContext) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

func (x *ErrorContext) GetStack() string {
	if x != nil {
		return x.Stack
	}
	return ""
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Service       string                 `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	SchemaVersion string                 `protobuf:"bytes,4,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	EventVersion  string                 `protobuf:"bytes,5,opt,name=event_version,json=eventVersion,proto3" json:"event_version,omitempty"`
	Version       string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	Environment   string                 `protobuf:"bytes,7,opt,name=environment,proto3" json:"environment,omitempty"`
	Event         string                 `protobuf:"bytes,8,opt,name=event,proto3" json:"event,omitempty"`
	Level         EventLevel             `protobuf:"varint,9,opt,name=level,proto3,enum=loxa.v1.EventLevel" json:"level,omitempty"`
	Outcome       EventOutcome           `protobuf:"varint,10,opt,name=outcome,proto3,enum=loxa.v1.EventOutcome" json:"outcome,omitempty"`
	DurationMs    float64                `protobuf:"fixed64,11,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	RequestId     string                 `protobuf:"bytes,12,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TraceId       string                 `protobuf:"bytes,13,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId        string                 `protobuf:"bytes,14,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	Http          *HttpContext           `protobuf:"bytes,15,opt,name=http,proto3" json:"http,omitempty"`
	Error         *ErrorContext          `protobuf:"bytes,16,opt,name=error,proto3" json:"error,omitempty"`
	Kind          EventKind              `protobuf:"varint,17,opt,name=kind,proto3,enum=loxa.v1.EventKind" json:"kind,omitempty"`
	User          *structpb.Struct       `protobuf:"bytes,18,opt,name=user,proto3" json:"user,omitempty"`
	Tenant        *structpb.Struct       `protobuf:"bytes,19,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Resource      *structpb.Struct       `protobuf:"bytes,20,opt,name=resource,proto3" json:"resource,omitempty"`
	Attrs         *structpb.Struct       `protobuf:"bytes,21,opt,name=attrs,proto3" json:"attrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_loxa_v1_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_loxa_v1_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_loxa_v1_event_proto_rawDescGZIP(), []int{2}
}

func (x *Event) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Event) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Event) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Event) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *Event) GetEventVersion() string {
	if x != nil {
		return x.EventVersion
	}
	return ""
}

func (x *Event) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Event) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *Event) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *Event) GetLevel() EventLevel {
	if x != nil {
		return x.Level
	}
	return EventLevel_EVENT_LEVEL_UNSPECIFIED
}

func (x *Event) GetOutcome() EventOutcome {
	if x != nil {
		return x.Outcome
	}
	return EventOutcome_EVENT_OUTCOME_UNSPECIFIED
}

func (x *Event) GetDurationMs() float64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *Event) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Event) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *Event) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *Event) GetHttp() *HttpContext {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *Event) GetError() *ErrorContext {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Event) GetKind() EventKind {
	if x != nil {
		return x.Kind
	}
	return EventKind_EVENT_KIND_UNSPECIFIED
}

func (x *Event) GetUser() *structpb.Struct {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Event) GetTenant() *structpb.Struct {
	if x != nil {
		return x.Tenant
	}
	return nil
}

func (x *Event) GetResource() *structpb.Struct {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *Event) GetAttrs() *structpb.Struct {
	if x != nil {
		return x.Attrs
	}
	return nil
}

var File_loxa_v1_event_proto protoreflect.FileDescriptor

const file_loxa_v1_event_proto_rawDesc = "" +
	"\n" +
	"\x13loxa/v1/event.proto\x12\aloxa.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd2\x01\n" +
	"\vHttpContext\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x14\n" +
	"\x05route\x18\x03 \x01(\tR\x05route\x12\x1f\n" +
	"\vstatus_code\x18\x04 \x01(\x05R\n" +
	"statusCode\x12\x1b\n" +
	"\tclient_ip\x18\x05 \x01(\tR\bclientIp\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x06 \x01(\tR\tuserAgent\x12\x10\n" +
	"\x03url\x18\a \x01(\tR\x03url\x12\x12\n" +
	"\x04host\x18\b \x01(\tR\x04host\"\x9a\x01\n" +
	"\fErrorContext\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x1c\n" +
	"\tretriable\x18\x04 \x01(\bR\tretriable\x12\x14\n" +
	"\x05cause\x18\x05 \x01(\tR\x05cause\x12\x14\n" +
	"\x05stack\x18\x06 \x01(\tR\x05stack\"\xa5\x06\n" +
	"\x05Event\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x18\n" +
	"\aservice\x18\x03 \x01(\tR\aservice\x12%\n" +
	"\x0eschema_version\x18\x04 \x01(\tR\rschemaVersion\x12#\n" +
	"\revent_version\x18\x05 \x01(\tR\feventVersion\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\x12 \n" +
	"\venvironment\x18\a \x01(\tR\venvironment\x12\x14\n" +
	"\x05event\x18\b \x01(\tR\x05event\x12)\n" +
	"\x05level\x18\t \x01(\x0e2\x13.loxa.v1.EventLevelR\x05level\x12/\n" +
	"\aoutcome\x18\n" +
	" \x01(\x0e2\x15.loxa.v1.EventOutcomeR\aoutcome\x12\x1f\n" +
	"\vduration_ms\x18\v \x01(\x01R\n" +
	"durationMs\x12\x1d\n" +
	"\n" +
	"request_id\x18\f \x01(\tR\trequestId\x12\x19\n" +
	"\btrace_id\x18\r \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x0e \x01(\tR\x06spanId\x12(\n" +
	"\x04http\x18\x0f \x01(\v2\x14.loxa.v1.HttpContextR\x04http\x12+\n" +
	"\x05error\x18\x10 \x01(\v2\x15.loxa.v1.ErrorContextR\x05error\x12&\n" +
	"\x04kind\x18\x11 \x01(\x0e2\x12.loxa.v1.EventKindR\x04kind\x12+\n" +
	"\x04user\x18\x12 \x01(\v2\x17.google.protobuf.StructR\x04user\x12/\n" +
	"\x06tenant\x18\x13 \x01(\v2\x17.google.protobuf.StructR\x06tenant\x123\n" +
	"\bresource\x18\x14 \x01(\v2\x17.google.protobuf.StructR\bresource\x12-\n" +
	"\x05attrs\x18\x15 \x01(\v2\x17.google.protobuf.StructR\x05attrs*\xd4\x01\n" +
	"\tEventKind\x12\x1a\n" +
	"\x16EVENT_KIND_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10EVENT_KIND_EVENT\x10\x01\x12\x13\n" +
	"\x0fEVENT_KIND_HTTP\x10\x02\x12\x12\n" +
	"\x0eEVENT_KIND_JOB\x10\x03\x12\x14\n" +
	"\x10EVENT_KIND_QUEUE\x10\x04\x12\x12\n" +
	"\x0eEVENT_KIND_CLI\x10\x05\x12\x13\n" +
	"\x0fEVENT_KIND_CRON\x10\x06\x12\x12\n" +
	"\x0eEVENT_KIND_LOG\x10\a\x12\x19\n" +
	"\x15EVENT_KIND_CHECKPOINT\x10\b*\x9a\x01\n" +
	"\n" +
	"EventLevel\x12\x1b\n" +
	"\x17EVENT_LEVEL_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11EVENT_LEVEL_DEBUG\x10\x01\x12\x14\n" +
	"\x10EVENT_LEVEL_INFO\x10\x02\x12\x14\n" +
	"\x10EVENT_LEVEL_WARN\x10\x03\x12\x15\n" +
	"\x11EVENT_LEVEL_ERROR\x10\x04\x12\x15\n" +
	"\x11EVENT_LEVEL_FATAL\x10\x05*\xd0\x01\n" +
	"\fEventOutcome\x12\x1d\n" +
	"\x19EVENT_OUTCOME_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15EVENT_OUTCOME_SUCCESS\x10\x01\x12\x17\n" +
	"\x13EVENT_OUTCOME_ERROR\x10\x02\x12\x19\n" +
	"\x15EVENT_OUTCOME_TIMEOUT\x10\x03\x12\x1b\n" +
	"\x17EVENT_OUTCOME_CANCELLED\x10\x04\x12\x1a\n" +
	"\x16EVENT_OUTCOME_REJECTED\x10\x05\x12\x19\n" +
	"\x15EVENT_OUTCOME_UNKNOWN\x10\x06B4Z2github.com/astraive/loxa/spec/proto/loxa/v1;loxav1b\x06proto3"

var (
	file_loxa_v1_event_proto_rawDescOnce sync.Once
	file_loxa_v1_event_proto_rawDescData []byte
)

func file_loxa_v1_event_proto_rawDescGZIP() []byte {
	file_loxa_v1_event_proto_rawDescOnce.Do(func() {
		file_loxa_v1_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_loxa_v1_event_proto_rawDesc), len(file_loxa_v1_event_proto_rawDesc)))
	})
	return file_loxa_v1_event_proto_rawDescData
}

var file_loxa_v1_event_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_loxa_v1_event_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_loxa_v1_event_proto_goTypes = []any{
	(EventKind)(0),                // 0: loxa.v1.EventKind
	(EventLevel)(0),               // 1: loxa.v1.EventLevel
	(EventOutcome)(0),             // 2: loxa.v1.EventOutcome
	(*HttpContext)(nil),           // 3: loxa.v1.HttpContext
	(*ErrorContext)(nil),          // 4: loxa.v1.ErrorContext
	(*Event)(nil),                 // 5: loxa.v1.Event
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 7: google.protobuf.Struct
}
var file_loxa_v1_event_proto_depIdxs = []int32{
	6,  // 0: loxa.v1.Event.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 1: loxa.v1.Event.level:type_name -> loxa.v1.EventLevel
	2,  // 2: loxa.v1.Event.outcome:type_name -> loxa.v1.EventOutcome
	3,  // 3: loxa.v1.Event.http:type_name -> loxa.v1.HttpContext
	4,  // 4: loxa.v1.Event.error:type_name -> loxa.v1.ErrorContext
	0,  // 5: loxa.v1.Event.kind:type_name -> loxa.v1.EventKind
	7,  // 6: loxa.v1.Event.user:type_name -> google.protobuf.Struct
	7,  // 7: loxa.v1.Event.tenant:type_name -> google.protobuf.Struct
	7,  // 8: loxa.v1.Event.resource:type_name -> google.protobuf.Struct
	7,  // 9: loxa.v1.Event.attrs:type_name -> google.protobuf.Struct
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_loxa_v1_event_proto_init() }
func file_loxa_v1_event_proto_init() {
	if File_loxa_v1_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_loxa_v1_event_proto_rawDesc), len(file_loxa_v1_event_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_loxa_v1_event_proto_goTypes,
		DependencyIndexes: file_loxa_v1_event_proto_depIdxs,
		EnumInfos:         file_loxa_v1_event_proto_enumTypes,
		MessageInfos:      file_loxa_v1_event_proto_msgTypes,
	}.Build()
	File_loxa_v1_event_proto = out.File
	file_loxa_v1_event_proto_goTypes = nil
	file_loxa_v1_event_proto_depIdxs = nil
}
