# ──────────────────────────────────────────────────────────────────────────────
# Core LOZA SDK types — all symbols explicitly imported for ruff & tooling
# ──────────────────────────────────────────────────────────────────────────────

# attr — attribute constructors, domain helpers, PascalCase aliases
from .attr import (
    String,
    Int,
    Int64,
    Uint64,
    Float64,
    Bool,
    Time,
    Duration,
    Any as AttrAny,
    Null,
    Group,
    SensitiveString,
    HashString,
    MarkSensitive,
    # generic typed attr constructors
    List,
    Map,
    Enum,
    ID,
    Hash,
    Redacted,
    AccountID,
    DeploymentID,
    HTTPRoute,
    HTTPMethod,
    HTTPPath,
    HTTPUserAgent,
    HTTPReferer,
    list_,
    map_,
    enum_,
    id_,
    hash_,
    redacted,
    account_id,
    deployment_id,
    http_route,
    http_method,
    http_path,
    http_user_agent,
    http_referer,
    # domain helpers (snake_case)
    payment_id,
    subscription_id,
    invoice_id,
    job_id,
    message_id,
    correlation_id,
    commit_sha,
    release,
    money,
    percent,
    bytes_attr,
    http_status,
    status_code,
    error_code,
    bucket,
    tags,
    masked,
    url,
    email_hash,
    ip_hash,
    region,
    checkout_cart_item_count,
    checkout_cart_total,
    checkout_payment_method,
    checkout_status,
    payment_provider,
    payment_method,
    payment_intent_id,
    payment_failure_code,
    payment_retry_attempt,
    billing_plan,
    billing_subscription_id,
    billing_invoice_id,
    billing_amount,
    billing_interval,
    agent_name,
    agent_provider,
    agent_model,
    agent_run_type,
    agent_tool_name,
    agent_tool_outcome,
    agent_input_tokens,
    agent_output_tokens,
    agent_cost,
    rag_index,
    rag_embedding_model,
    rag_chunks_retrieved,
    rag_top_score,
    rag_query_hash,
    rag_citation_count,
    rag_retrieval_latency,
    # PascalCase aliases
    PaymentID,
    SubscriptionID,
    InvoiceID,
    JobID,
    MessageID,
    CorrelationID,
    CommitSHA,
    Release,
    Money,
    Percent,
    Bytes,
    HTTPStatus,
    StatusCode,
    Bucket,
    Tags,
    Masked,
    URL,
    EmailHash,
    IPHash,
    Region,
    CheckoutCartItemCount,
    CheckoutCartTotal,
    CheckoutPaymentMethod,
    CheckoutStatus,
    PaymentProvider,
    PaymentMethod,
    PaymentIntentID,
    PaymentFailureCode,
    PaymentRetryAttempt,
    BillingPlan,
    BillingSubscriptionID,
    BillingInvoiceID,
    BillingAmount,
    BillingInterval,
    AgentName,
    AgentProvider,
    AgentModel,
    AgentRunType,
    AgentToolName,
    AgentToolOutcome,
    AgentInputTokens,
    AgentOutputTokens,
    AgentCost,
    RAGIndex,
    RAGEmbeddingModel,
    RAGChunksRetrieved,
    RAGTopScore,
    RAGQueryHash,
    RAGCitationCount,
    RAGRetrievalLatency,
)

# logger
from .logger import Logger

# config — config classes, constants, factories
from .config import (
    CanonicalWins,
    UserWins,
    FirstWins,
    LastWins,
    KeepBoth,
    ErrorOnDuplicate,
    ExpandDotKeys,
    PreserveDotKeys,
    SnakeCaseKeys,
    CamelCaseKeys,
    StatsHandler,
    DeliveryFailureHandler,
    AsyncConfig,
    SecurityConfig,
    FieldNamingConfig,
    Config,
    LOZA_EVENT_VERSION,
    LOZA_INGEST_API_VERSION,
    LOZA_SPEC_VERSION,
    load_layered_config,
    new_client,
)

# config_options — functional options for Config
from .config_options import (
    WithService,
    WithVersion,
    WithEnvironment,
    WithSink,
    WithSampler,
    WithRedactor,
    WithMetrics,
    WithSchema,
    WithEventSchema,
    WithAsync,
    WithCollectorEndpoint,
    WithDuplicatePolicy,
    WithStatsHandler,
    WithDeploymentID,
    WithIncludeHost,
    WithPanicRecovery,
    WithExitOnFatal,
    WithRelease,
    WithNamespace,
    WithApiKey,
    WithOtelBridge,
    WithRetry,
    WithTimeout,
    WithQueueSize,
    WithFlushInterval,
    WithBatchSize,
    WithLogger,
    Disabled,
    FromEnv,
    with_service,
    with_version,
    with_environment,
    with_sink,
    with_sampler,
    with_redactor,
    with_metrics,
    with_schema,
    with_event_schema,
    with_async,
    with_collector_endpoint,
    with_duplicate_policy,
    with_stats_handler,
    with_deployment_id,
    with_include_host,
    with_panic_recovery,
    with_exit_on_fatal,
    with_release,
    with_namespace,
    with_api_key,
    with_otel_bridge,
    with_retry,
    with_timeout,
    with_queue_size,
    with_flush_interval,
    with_batch_size,
    with_logger,
    disabled,
    from_env,
)

# context — event context helpers
from .context import (
    FromContext,
    HasEvent,
    EventID,
    RequestIDFromContext,
    TraceIDFromContext,
    SpanIDFromContext,
)

# event — core event types
from .event import (
    Attr,
    Params,
    EventContext,
    EVENT_CREATED,
    EVENT_ACTIVE,
    EVENT_FINISHED,
    EVENT_EMITTING,
    EVENT_EMITTED,
    EVENT_FAILED_VALIDATION,
    EVENT_DELIVERY_FAILED,
    sanitize_event,
)

# errors — typed errors
from .errors import (
    DuplicateEmitError,
    EventAlreadyFinishedError,
    EventClosedError,
    EventValidationError,
    ErrorInfo,
    LozaError,
)

# level — log levels
from .level import (
    LevelDebug,
    LevelInfo,
    LevelNotice,
    LevelWarn,
    LevelError,
    LevelFatal,
    ParseLevel,
)

# redactor — PII redaction
from .redactor import (
    default_redactor,
    redact,
    redact_keys,
    hash_keys,
    mask_keys,
    drop_keys,
    redact_patterns,
    compose_redactors,
    REDACTED_VALUE,
    sensitive_attrs_redactor,
)

# sampler — sampling strategies
from .sampler import (
    sample_all,
    sample_none,
    sample_random,
    sample_rate,
    sample_errors,
    sample_slow_requests,
    sample_status_codes,
    sample_routes,
    sample_users,
    sample_tenants,
    sample_feature_flag,
    sample_by_header,
    any_sampler,
    all_sampler,
    not_sampler,
    sample_rate_limited,
    sample_by_event,
    sample_by_outcome,
    should_sample,
    allow_fields,
    block_fields,
    SampleByEvent,
    SampleByOutcome,
    ShouldSample,
    AllowFields,
    BlockFields,
)

# schema — event schemas
from .schema import (
    Schema,
    SchemaFunc,
    EventView,
    DefaultSchema,
    FlatSchema,
    NestedSchema,
    ECSchema,
    OTelLogSchema,
    DatadogSchema,
    CallableSchema,
    custom_schema,
)

# metrics
from .metric import MetricsCollector, MetricsSnapshot

# standard_sinks
from .standard_sinks import StderrSink, RotatingFileSink, CollectorSink
