"""Emitter: generate lql/src/schema.rs from the spec contract.

This ensures the LQL crate's schema module stays in sync with the canonical
Loza event fields defined in the spec.
"""

from __future__ import annotations

from typing import Any


def render_lql_schema(contract: dict[str, Any]) -> str:
    """Generate a Rust module for the Loza event schema used by LQL."""
    fields = contract.get("canonical_fields", [])
    enums = contract.get("enums", {})

    lines = [
        "// Auto-generated by spec/codegen/emitters/lql_schema.py — DO NOT EDIT",
        "// Source: spec/schema/event.schema.json",
        "",
        "use std::collections::HashMap;",
        "",
        "/// Metadata for a single field in the Loza event schema.",
        "#[derive(Debug, Clone)]",
        "pub struct FieldInfo {",
        "    pub name: &'static str,",
        "    pub field_type: FieldType,",
        "    pub description: &'static str,",
        "}",
        "",
        "#[derive(Debug, Clone, PartialEq)]",
        "pub enum FieldType {",
        "    String,",
        "    Integer,",
        "    Float,",
        "    Boolean,",
        "    Timestamp,",
        "    Duration,",
        "    Array,",
        "    Object,",
        "}",
        "",
        "/// The full Loza event schema, used for validation and column mapping.",
        "pub struct Schema {",
        "    pub table: &'static str,",
        "    pub fields: Vec<FieldInfo>,",
        "}",
        "",
    ]

    # Build the static field list
    lines.append("fn build_fields() -> Vec<FieldInfo> {")
    lines.append("    vec![")
    for field_name in fields:
        ft = _field_type(field_name)
        desc = _field_description(field_name)
        lines.append(f'        FieldInfo {{ name: "{field_name}", field_type: FieldType::{ft}, description: "{desc}" }},')
    lines.append("    ]")
    lines.append("}")
    lines.append("")

    # Schema impl
    lines.append("impl Schema {")
    lines.append("    /// Create the default DuckDB schema.")
    lines.append("    pub fn duckdb_default() -> Self {")
    lines.append("        Self { table: \"events\", fields: build_fields() }")
    lines.append("    }")
    lines.append("")
    lines.append("    /// Create the default ClickHouse schema.")
    lines.append("    pub fn clickhouse_default() -> Self {")
    lines.append("        Self { table: \"loza_events\", fields: build_fields() }")
    lines.append("    }")
    lines.append("")
    lines.append("    /// Check if a field name exists in the schema.")
    lines.append("    pub fn has_field(&self, name: &str) -> bool {")
    lines.append("        self.fields.iter().any(|f| f.name == name)")
    lines.append("    }")
    lines.append("")
    lines.append("    /// Get all known field names.")
    lines.append("    pub fn field_names(&self) -> Vec<&'static str> {")
    lines.append("        self.fields.iter().map(|f| f.name).collect()")
    lines.append("    }")
    lines.append("}")
    lines.append("")

    # Known enum values for autocomplete
    lines.append("/// Known enum values for each field (for autocomplete/validation).")
    lines.append("pub fn known_enum_values(field: &str) -> Option<Vec<&'static str>> {")
    lines.append("    match field {")
    for enum_name, values in enums.items():
        if isinstance(values, list) and values:
            rust_vals = ", ".join(f'"{v}"' for v in sorted(values))
            field_name = _enum_to_field(enum_name)
            lines.append(f'        "{field_name}" => Some(vec![{rust_vals}]),')
    lines.append("        _ => None,")
    lines.append("    }")
    lines.append("}")

    return "\n".join(lines) + "\n"


# ── Helpers ──────────────────────────────────────────────────────────────────

_FIELD_TYPES = {
    "event_id": "String",
    "timestamp": "Timestamp",
    "service": "String",
    "version": "String",
    "environment": "String",
    "release": "String",
    "deployment_id": "String",
    "region": "String",
    "host": "String",
    "event": "String",
    "kind": "String",
    "level": "String",
    "outcome": "String",
    "event_state": "String",
    "message": "String",
    "error_code": "String",
    "error_type": "String",
    "error_message": "String",
    "duration_ms": "Float",
    "started_at": "Timestamp",
    "finished_at": "Timestamp",
    "request_id": "String",
    "trace_id": "String",
    "span_id": "String",
    "incident_id": "String",
    "method": "String",
    "path": "String",
    "route": "String",
    "status_code": "Integer",
    "user_agent": "String",
    "http_status": "Integer",
    "sdk_name": "String",
    "sdk_version": "String",
    "schema_version": "String",
    "event_version": "String",
}

_FIELD_DESCRIPTIONS = {
    "event_id": "Unique event identifier",
    "timestamp": "Event timestamp (ISO 8601)",
    "service": "Service name",
    "version": "Service version",
    "environment": "Deployment environment",
    "release": "Release identifier",
    "deployment_id": "Deployment identifier",
    "region": "Deployment region",
    "host": "Host name",
    "event": "Event name",
    "kind": "Event kind",
    "level": "Log level",
    "outcome": "Event outcome",
    "event_state": "Lifecycle state",
    "message": "Human-readable message",
    "error_code": "Error code",
    "error_type": "Error type",
    "error_message": "Error message",
    "duration_ms": "Duration in milliseconds",
    "started_at": "Event start time",
    "finished_at": "Event finish time",
    "request_id": "Request identifier",
    "trace_id": "Distributed trace identifier",
    "span_id": "Span identifier",
    "incident_id": "Incident identifier",
    "method": "HTTP method",
    "path": "HTTP path",
    "route": "HTTP route",
    "status_code": "HTTP status code",
    "user_agent": "User agent string",
    "http_status": "HTTP status",
    "sdk_name": "SDK name",
    "sdk_version": "SDK version",
    "schema_version": "Event schema version",
    "event_version": "Event version",
}


def _field_type(name: str) -> str:
    return _FIELD_TYPES.get(name, "String")


def _field_description(name: str) -> str:
    return _FIELD_DESCRIPTIONS.get(name, f"{name} field")


def _enum_to_field(enum_name: str) -> str:
    """Map enum names from the contract to event field names."""
    mapping = {
        "kinds": "kind",
        "levels": "level",
        "outcomes": "outcome",
        "event_states": "event_state",
        "partial_reasons": "partial_reason",
    }
    return mapping.get(enum_name, enum_name)
