// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: loxa/v1/cortex.proto

package loxav1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CortexService_Healthz_FullMethodName        = "/loxa.v1.CortexService/Healthz"
	CortexService_IngestEvent_FullMethodName    = "/loxa.v1.CortexService/IngestEvent"
	CortexService_IngestBatch_FullMethodName    = "/loxa.v1.CortexService/IngestBatch"
	CortexService_Reconstruct_FullMethodName    = "/loxa.v1.CortexService/Reconstruct"
	CortexService_GetGraph_FullMethodName       = "/loxa.v1.CortexService/GetGraph"
	CortexService_RecordFeedback_FullMethodName = "/loxa.v1.CortexService/RecordFeedback"
	CortexService_StreamEvents_FullMethodName   = "/loxa.v1.CortexService/StreamEvents"
	CortexService_QueryLifecycle_FullMethodName = "/loxa.v1.CortexService/QueryLifecycle"
)

// CortexServiceClient is the client API for CortexService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CortexServiceClient interface {
	Healthz(ctx context.Context, in *HealthzRequest, opts ...grpc.CallOption) (*HealthzResponse, error)
	IngestEvent(ctx context.Context, in *IngestEventRequest, opts ...grpc.CallOption) (*IngestEventResponse, error)
	IngestBatch(ctx context.Context, in *IngestBatchRequest, opts ...grpc.CallOption) (*IngestBatchResponse, error)
	Reconstruct(ctx context.Context, in *ReconstructRequest, opts ...grpc.CallOption) (*ReconstructResponse, error)
	GetGraph(ctx context.Context, in *GetGraphRequest, opts ...grpc.CallOption) (*GetGraphResponse, error)
	RecordFeedback(ctx context.Context, in *RecordFeedbackRequest, opts ...grpc.CallOption) (*RecordFeedbackResponse, error)
	StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
	QueryLifecycle(ctx context.Context, in *QueryLifecycleRequest, opts ...grpc.CallOption) (*QueryLifecycleResponse, error)
}

type cortexServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCortexServiceClient(cc grpc.ClientConnInterface) CortexServiceClient {
	return &cortexServiceClient{cc}
}

func (c *cortexServiceClient) Healthz(ctx context.Context, in *HealthzRequest, opts ...grpc.CallOption) (*HealthzResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthzResponse)
	err := c.cc.Invoke(ctx, CortexService_Healthz_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cortexServiceClient) IngestEvent(ctx context.Context, in *IngestEventRequest, opts ...grpc.CallOption) (*IngestEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestEventResponse)
	err := c.cc.Invoke(ctx, CortexService_IngestEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cortexServiceClient) IngestBatch(ctx context.Context, in *IngestBatchRequest, opts ...grpc.CallOption) (*IngestBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestBatchResponse)
	err := c.cc.Invoke(ctx, CortexService_IngestBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cortexServiceClient) Reconstruct(ctx context.Context, in *ReconstructRequest, opts ...grpc.CallOption) (*ReconstructResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReconstructResponse)
	err := c.cc.Invoke(ctx, CortexService_Reconstruct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cortexServiceClient) GetGraph(ctx context.Context, in *GetGraphRequest, opts ...grpc.CallOption) (*GetGraphResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGraphResponse)
	err := c.cc.Invoke(ctx, CortexService_GetGraph_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cortexServiceClient) RecordFeedback(ctx context.Context, in *RecordFeedbackRequest, opts ...grpc.CallOption) (*RecordFeedbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordFeedbackResponse)
	err := c.cc.Invoke(ctx, CortexService_RecordFeedback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cortexServiceClient) StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CortexService_ServiceDesc.Streams[0], CortexService_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamEventsRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CortexService_StreamEventsClient = grpc.ServerStreamingClient[Event]

func (c *cortexServiceClient) QueryLifecycle(ctx context.Context, in *QueryLifecycleRequest, opts ...grpc.CallOption) (*QueryLifecycleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryLifecycleResponse)
	err := c.cc.Invoke(ctx, CortexService_QueryLifecycle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CortexServiceServer is the server API for CortexService service.
// All implementations must embed UnimplementedCortexServiceServer
// for forward compatibility.
type CortexServiceServer interface {
	Healthz(context.Context, *HealthzRequest) (*HealthzResponse, error)
	IngestEvent(context.Context, *IngestEventRequest) (*IngestEventResponse, error)
	IngestBatch(context.Context, *IngestBatchRequest) (*IngestBatchResponse, error)
	Reconstruct(context.Context, *ReconstructRequest) (*ReconstructResponse, error)
	GetGraph(context.Context, *GetGraphRequest) (*GetGraphResponse, error)
	RecordFeedback(context.Context, *RecordFeedbackRequest) (*RecordFeedbackResponse, error)
	StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[Event]) error
	QueryLifecycle(context.Context, *QueryLifecycleRequest) (*QueryLifecycleResponse, error)
	mustEmbedUnimplementedCortexServiceServer()
}

// UnimplementedCortexServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCortexServiceServer struct{}

func (UnimplementedCortexServiceServer) Healthz(context.Context, *HealthzRequest) (*HealthzResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Healthz not implemented")
}
func (UnimplementedCortexServiceServer) IngestEvent(context.Context, *IngestEventRequest) (*IngestEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IngestEvent not implemented")
}
func (UnimplementedCortexServiceServer) IngestBatch(context.Context, *IngestBatchRequest) (*IngestBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IngestBatch not implemented")
}
func (UnimplementedCortexServiceServer) Reconstruct(context.Context, *ReconstructRequest) (*ReconstructResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reconstruct not implemented")
}
func (UnimplementedCortexServiceServer) GetGraph(context.Context, *GetGraphRequest) (*GetGraphResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGraph not implemented")
}
func (UnimplementedCortexServiceServer) RecordFeedback(context.Context, *RecordFeedbackRequest) (*RecordFeedbackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordFeedback not implemented")
}
func (UnimplementedCortexServiceServer) StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedCortexServiceServer) QueryLifecycle(context.Context, *QueryLifecycleRequest) (*QueryLifecycleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryLifecycle not implemented")
}
func (UnimplementedCortexServiceServer) mustEmbedUnimplementedCortexServiceServer() {}
func (UnimplementedCortexServiceServer) testEmbeddedByValue()                       {}

// UnsafeCortexServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CortexServiceServer will
// result in compilation errors.
type UnsafeCortexServiceServer interface {
	mustEmbedUnimplementedCortexServiceServer()
}

func RegisterCortexServiceServer(s grpc.ServiceRegistrar, srv CortexServiceServer) {
	// If the following call panics, it indicates UnimplementedCortexServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CortexService_ServiceDesc, srv)
}

func _CortexService_Healthz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthzRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CortexServiceServer).Healthz(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CortexService_Healthz_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CortexServiceServer).Healthz(ctx, req.(*HealthzRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CortexService_IngestEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CortexServiceServer).IngestEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CortexService_IngestEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CortexServiceServer).IngestEvent(ctx, req.(*IngestEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CortexService_IngestBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CortexServiceServer).IngestBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CortexService_IngestBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CortexServiceServer).IngestBatch(ctx, req.(*IngestBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CortexService_Reconstruct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReconstructRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CortexServiceServer).Reconstruct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CortexService_Reconstruct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CortexServiceServer).Reconstruct(ctx, req.(*ReconstructRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CortexService_GetGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGraphRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CortexServiceServer).GetGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CortexService_GetGraph_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CortexServiceServer).GetGraph(ctx, req.(*GetGraphRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CortexService_RecordFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordFeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CortexServiceServer).RecordFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CortexService_RecordFeedback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CortexServiceServer).RecordFeedback(ctx, req.(*RecordFeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CortexService_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CortexServiceServer).StreamEvents(m, &grpc.GenericServerStream[StreamEventsRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CortexService_StreamEventsServer = grpc.ServerStreamingServer[Event]

func _CortexService_QueryLifecycle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLifecycleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CortexServiceServer).QueryLifecycle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CortexService_QueryLifecycle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CortexServiceServer).QueryLifecycle(ctx, req.(*QueryLifecycleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CortexService_ServiceDesc is the grpc.ServiceDesc for CortexService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CortexService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "loxa.v1.CortexService",
	HandlerType: (*CortexServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Healthz",
			Handler:    _CortexService_Healthz_Handler,
		},
		{
			MethodName: "IngestEvent",
			Handler:    _CortexService_IngestEvent_Handler,
		},
		{
			MethodName: "IngestBatch",
			Handler:    _CortexService_IngestBatch_Handler,
		},
		{
			MethodName: "Reconstruct",
			Handler:    _CortexService_Reconstruct_Handler,
		},
		{
			MethodName: "GetGraph",
			Handler:    _CortexService_GetGraph_Handler,
		},
		{
			MethodName: "RecordFeedback",
			Handler:    _CortexService_RecordFeedback_Handler,
		},
		{
			MethodName: "QueryLifecycle",
			Handler:    _CortexService_QueryLifecycle_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _CortexService_StreamEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "loxa/v1/cortex.proto",
}
