package metrics

const (
	RequestsTotalName          = "loza_collector_requests_total"
	RequestsAuthErrorsName     = "loza_collector_requests_auth_errors_total"
	RequestsLimitedName        = "loza_collector_requests_limited_total"
	RequestsThrottledName      = "loza_collector_requests_throttled_total"
	EventsAcceptedName         = "loza_collector_events_accepted_total"
	EventsInvalidName          = "loza_collector_events_invalid_total"
	EventsRejectedName         = "loza_collector_events_rejected_total"
	EventsDedupedName          = "loza_collector_events_deduped_total"
	SinkWriteErrorsName        = "loza_collector_sink_write_errors_total"
	DiskFullErrorsName         = "loza_collector_disk_full_errors_total"
	ParseErrorsName            = "loza_collector_parse_errors_total"
	SpoolBytesName             = "loza_collector_spool_bytes"
	QueueBytesName             = "loza_collector_queue_bytes"
	InflightRequestsName       = "loza_collector_inflight_requests"
	InflightEventsName         = "loza_collector_inflight_events"
	SinkHealthName             = "loza_collector_sink_health"
	DiskHealthName             = "loza_collector_disk_health"
	SpoolHealthName            = "loza_collector_spool_health"
	ReadyName                  = "loza_collector_ready"
	SchemaValidationsName      = "loza_collector_schema_validations_total"
	SchemaWarningsName         = "loza_collector_schema_warnings_total"
	SchemaRejectionsName       = "loza_collector_schema_rejections_total"
	DLQWritesName              = "loza_collector_dlq_writes_total"
	DLQWriteFailuresName       = "loza_collector_dlq_write_failures_total"
	QuarantineWritesName       = "loza_collector_quarantine_writes_total"
	RetryAttemptsName          = "loza_collector_retry_attempts_total"
	RetrySuccessesName         = "loza_collector_retry_successes_total"
	RetryFailuresName          = "loza_collector_retry_failures_total"
	CortexBridgeFlushesName    = "loza_collector_cortex_bridge_flushes_total"
	CortexBridgeEventsName     = "loza_collector_cortex_bridge_events_total"
	CortexBridgeErrorsName     = "loza_collector_cortex_bridge_errors_total"
	CortexBridgeQueueDepthName = "loza_collector_cortex_bridge_queue_depth"
)
