"""Default configuration values."""

from __future__ import annotations

DEFAULT_SERVICE = ""
DEFAULT_VERSION = ""
DEFAULT_ENVIRONMENT = "development"
DEFAULT_LEVEL = "info"
DEFAULT_REGION = ""
DEFAULT_DUPLICATE_POLICY = "canonical_wins"
DEFAULT_ASYNC_QUEUE_SIZE = 8192
DEFAULT_ASYNC_WORKERS = 1
DEFAULT_MAX_BATCH_BYTES = 256 * 1024
DEFAULT_MAX_EVENT_BYTES = 256 * 1024
DEFAULT_MAX_FIELD_BYTES = 4096
DEFAULT_MAX_ATTR_COUNT = 512
DEFAULT_MAX_CHECKPOINTS = 32
