project_name: loza
version: 0.3.1
archives:
  - format: tar.gz
builds:
  - id: loza-collector
    dir: ./cmd/loza-collector
    binary: loza-collector
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
  - id: loza-worker
    dir: ./cmd/loza-worker
    binary: loza-worker
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
  - id: loza
    dir: ./cmd/loza
    binary: loza
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
  - id: loza-loadgen
    dir: ./cmd/loza-loadgen
    binary: loza-loadgen
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
dockers:
  - image: astraive/loza
    dockerfile: Dockerfile
    goos: linux
    goarch:
      - amd64
      - arm64
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  filters:
    exclude:
      - '^docs:'
      - '^chore:'
      - '^refactor:'
release:
  github:
    owner: Astraive
    name: loza
  draft: true
