{{- if and .Values.collector.enabled .Values.collector.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "loxa.fullname" . }}-collector
  labels:
    {{- include "loxa.labels" . | nindent 4 }}
    app.kubernetes.io/component: collector
spec:
  {{- if .Values.collector.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.collector.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.collector.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.collector.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "loxa.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: collector
{{- end }}
