apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - schema-service-configmap.yaml
  - schema-service-deployment.yaml
  - schema-service-service.yaml
  - stager-configmap.yaml
  - stager-deployment.yaml
