apiVersion: v1
kind: ConfigMap
metadata:
  name: loza-schema-service-config
  labels:
    app.kubernetes.io/name: schema-service
    app.kubernetes.io/part-of: loza
data:
  SCHEMA_SERVICE_HOST: "0.0.0.0"
  SCHEMA_SERVICE_PORT: "9315"
