{{- if and .Values.persistence.enabled .Values.collector.enabled (not .Values.persistence.collector.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "loza.fullname" . }}-collector
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "loza.labels" . | nindent 4 }}
    app.kubernetes.io/component: collector
spec:
  accessModes:
    - {{ .Values.persistence.collector.accessMode }}
  {{- with .Values.persistence.collector.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.collector.size }}
{{- end }}
{{- if and .Values.persistence.enabled .Values.worker.enabled (not .Values.persistence.worker.existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "loza.fullname" . }}-worker
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "loza.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  accessModes:
    - {{ .Values.persistence.worker.accessMode }}
  {{- with .Values.persistence.worker.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.worker.size }}
{{- end }}
