{{- if and .Values.collector.enabled .Values.collector.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "loza.fullname" . }}-collector
  labels:
    {{- include "loza.labels" . | nindent 4 }}
    app.kubernetes.io/component: collector
    {{- with .Values.collector.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "loza.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: collector
  endpoints:
    - port: metrics
      interval: {{ .Values.collector.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.collector.serviceMonitor.scrapeTimeout }}
      path: /metrics
{{- end }}
