apiVersion: v1
kind: Service
metadata:
  name: loxa-collector
  labels:
    app.kubernetes.io/name: loxa-collector
    app.kubernetes.io/component: collector
spec:
  type: ClusterIP
  ports:
    - port: 9308
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: loxa-collector
    app.kubernetes.io/component: collector
