{{- if .Values.storage.postgresql.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cortex.fullname" . }}-secrets
  labels:
    {{- include "cortex.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.storage.postgresql.password | b64enc | quote }}
{{- end }}
