package database

import (
	"context"
	"database/sql"
	"fmt"
	"time"

	"github.com/ClickHouse/clickhouse-go/v2/lib/driver"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

// Metadata is safe to expose through the Collector API.
type Metadata struct {
	Name         string   `json:"name"`
	Backend      string   `json:"backend"`
	Host         string   `json:"host,omitempty"`
	Port         int      `json:"port,omitempty"`
	Path         string   `json:"path,omitempty"`
	Database     string   `json:"database,omitempty"`
	Table        string   `json:"table,omitempty"`
	Enabled      bool     `json:"enabled"`
	Primary      bool     `json:"primary"`
	Capabilities []string `json:"capabilities"`
}

// Result is the backend-neutral query result envelope.
type Result struct {
	Columns []string
	Rows    [][]any
}

// Connection is the Collector-owned database contract. Query receives only
// parameterized SQL generated by the LQL compiler.
type Connection interface {
	Backend() string
	Metadata() Metadata
	Query(context.Context, string, ...any) (Result, error)
	Ping(context.Context) error
	Close(context.Context) error
}

func collectRows(columns []string, next func() bool, scan func(...any) error, rowErr func() error, close func(), limit int) (Result, error) {
	defer close()
	result := Result{Columns: append([]string(nil), columns...), Rows: make([][]any, 0)}
	for next() {
		values := make([]any, len(columns))
		pointers := make([]any, len(columns))
		for i := range values {
			pointers[i] = &values[i]
		}
		if err := scan(pointers...); err != nil {
			return Result{}, err
		}
		for i, value := range values {
			if bytes, ok := value.([]byte); ok {
				values[i] = string(bytes)
			}
		}
		result.Rows = append(result.Rows, values)
		if limit > 0 && len(result.Rows) >= limit {
			break
		}
	}
	if err := rowErr(); err != nil {
		return Result{}, err
	}
	return result, nil
}

func QuerySQLRows(rows *sql.Rows, limit int) (Result, error) {
	columns, err := rows.Columns()
	if err != nil {
		_ = rows.Close()
		return Result{}, err
	}
	return collectRows(columns, rows.Next, rows.Scan, rows.Err, func() { _ = rows.Close() }, limit)
}

func QueryPostgresRows(rows pgx.Rows, limit int) (Result, error) {
	columns := rows.FieldDescriptions()
	names := make([]string, 0, len(columns))
	for _, field := range columns {
		names = append(names, field.Name)
	}
	return collectRows(names, rows.Next, rows.Scan, rows.Err, rows.Close, limit)
}

type clickHouseRows interface {
	Columns() []string
	Next() bool
	Scan(...any) error
	Err() error
	Close() error
}

func QueryClickHouseRows(rows clickHouseRows, limit int) (Result, error) {
	return collectRows(rows.Columns(), rows.Next, rows.Scan, rows.Err, func() { _ = rows.Close() }, limit)
}

type SQL struct {
	DB   *sql.DB
	Info Metadata
}

func (c *SQL) Backend() string    { return c.Info.Backend }
func (c *SQL) Metadata() Metadata { return c.Info }
func (c *SQL) Query(ctx context.Context, query string, args ...any) (Result, error) {
	rows, err := c.DB.QueryContext(ctx, query, args...)
	if err != nil {
		return Result{}, err
	}
	return QuerySQLRows(rows, 0)
}
func (c *SQL) Exec(ctx context.Context, query string, args ...any) error {
	_, err := c.DB.ExecContext(ctx, query, args...)
	return err
}
func (c *SQL) Ping(ctx context.Context) error { return c.DB.PingContext(ctx) }
func (c *SQL) Close(context.Context) error    { return c.DB.Close() }

type Postgres struct {
	Pool *pgxpool.Pool
	Info Metadata
}

func (c *Postgres) Backend() string    { return c.Info.Backend }
func (c *Postgres) Metadata() Metadata { return c.Info }
func (c *Postgres) Query(ctx context.Context, query string, args ...any) (Result, error) {
	rows, err := c.Pool.Query(ctx, query, args...)
	if err != nil {
		return Result{}, err
	}
	return QueryPostgresRows(rows, 0)
}
func (c *Postgres) Exec(ctx context.Context, query string, args ...any) error {
	_, err := c.Pool.Exec(ctx, query, args...)
	return err
}
func (c *Postgres) Ping(ctx context.Context) error { return c.Pool.Ping(ctx) }
func (c *Postgres) Close(context.Context) error    { c.Pool.Close(); return nil }

type ClickHouse struct {
	Conn driver.Conn
	Info Metadata
}

func (c *ClickHouse) Exec(ctx context.Context, query string, args ...any) error {
	return c.Conn.Exec(ctx, query, args...)
}
func (c *ClickHouse) Backend() string    { return c.Info.Backend }
func (c *ClickHouse) Metadata() Metadata { return c.Info }
func (c *ClickHouse) Query(ctx context.Context, query string, args ...any) (Result, error) {
	rows, err := c.Conn.Query(ctx, query, args...)
	if err != nil {
		return Result{}, err
	}
	return QueryClickHouseRows(rows, 0)
}
func (c *ClickHouse) Ping(ctx context.Context) error { return c.Conn.Ping(ctx) }
func (c *ClickHouse) Close(context.Context) error    { return c.Conn.Close() }

func BoundedContext(parent context.Context, timeout time.Duration) (context.Context, context.CancelFunc) {
	if timeout <= 0 {
		timeout = 10 * time.Second
	}
	return context.WithTimeout(parent, timeout)
}

func ValidateQuery(query string) error {
	if query == "" {
		return fmt.Errorf("query is required")
	}
	return nil
}
